### PR TITLE
Fix newline in README.md

### PR DESCRIPTION
**Pull request by Ruthenic**

### CODE REVIEW

**Comment by Beefers** [comment]
balls

**Comment by nomyTx** [comment]
can i put my ball in yo jaw?

**Comment by Ruthenic** [comment]
> can i put my ball in yo jaw?

Yes, as long as you are named Angel Dust and have white fur.

**Comment by SomeAspy** [comment]
see c68b6f2

**Comment by nomyTx** [comment]
> > can i put my ball in yo jaw?
> 
> Yes, as long as you are named Angel Dust and have white fur.

:trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Pull request closed without merging**
